version: '3'
services:
  downloader:
    build:
      context: ${DEX_SOURCES_PATH}/target/docker/stage
      dockerfile: Dockerfile
    volumes:
      - /data/downloader/conf/env.conf:/downloader/conf/conf.env:ro
